export * from './AlfaBankLogoMIcon';
export * from './ApplePayLIcon';
export * from './GooglePayLIcon';
export * from './MaestroLColorIcon';
export * from './MastercardLColorIcon';
export * from './MastercardLIcon';
export * from './MirXxlIcon';
export * from './PaypassXsIcon';
export * from './VisaXxlIcon';
